apiVersion: v1
kind: Namespace
metadata:
  name: iicpc
  labels:
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: iicpc-compute-resources
  namespace: iicpc
spec:
  hard:
    requests.cpu: "32"
    requests.memory: 64Gi
    limits.cpu: "64"
    limits.memory: 128Gi
    pods: "100"
    services: "30"
